apiVersion: batch/v1
kind: Job
metadata:
  name: taskapp-migration
  namespace: taskapp
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/ts-a-devops/taskapp-backend:5d6b8fc
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_HOST
              value: postgres-service
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: taskapp
            - name: DATABASE_USER
              value: taskapp
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: DB_PASSWORD